### ISSUE TITLE
Comments are broken/won't load

### ISSUE THREAD

**Issue by HairyMilkshakes** [NewPipeX/NewPipeX#30]
### Checklist

- [X] I am able to reproduce the bug with the latest Release of this fork: [CLICK THIS LINK](https://github.com/javulticat/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream `NewPipe`](https://github.com/TeamNewPipe/NewPipe/releases).
- [X] I made sure that there are *no existing bug reports* - [open](https://github.com/javulticat/NewPipe/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [closed](https://github.com/javulticat/NewPipe/issues?q=is%3Aissue+is%3Aclosed+label%3Abug) - which I could contribute my information to.
- [X] I made sure that this bug is *not* [a known issue with upstream `NewPipe`](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aopen+label%3Abug).
- [X] I have taken the time to completely fill in the required details. I understand that my bug report may be dismissed otherwise.
- [X] I have limited the scope of this bug report to a single bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/javulticat/NewPipe/blob/sponsorblock/.github/CONTRIBUTING.md).

### Affected release

v0.26.1-2

### App version

v0.26.1-2

### Steps to reproduce the bug

1. Go to any video
2. Let it load
3. Comments don't load.

### Expected behavior

Comments should load

### Actual behavior

An error message occurs and you can report it. 

### Screenshots/Screen recordings

<img alt="CCrPVnraXI" src="https://github.com/javulticat/NewPipe/assets/13473043/b7ba5602-121e-45d4-ac37-b3a3131fe3f8" width=308 />

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux samsung/c2qzhx/c2q:13/TP1A.220624.014/N9860ZSU6HWH9:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1807)
	at android.app.Activity.startActivityForResult(Activity.java:5596)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5554)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:6052)
	at android.app.Activity.startActivity(Activity.java:6019)
	at org.schabi.newpipe.error.ErrorUtil$Companion.openActivity(ErrorUtil.kt:49)
	at org.schabi.newpipe.error.ErrorUtil$Companion.showSnackbar$lambda$0(ErrorUtil.kt:168)
	at org.schabi.newpipe.error.ErrorUtil$Companion.$r8$lambda$hbVLiP6-HtFc17h3_yyNDsmaIY8(ErrorUtil.kt:0)
	at org.schabi.newpipe.error.ErrorUtil$Companion$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar.$r8$lambda$4rINiMZz55Dc47hSTCuz-ALWyEw(Snackbar.java:0)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16220)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.os.TransactionTooLargeException: data parcel size 1242024 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:662)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2790)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1801)
	... 26 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13/OneUI 5.1

### Affected device model

Note20 Ultra

### Additional information

N/A

**Comment by yoshimo** [comment]
it will be fixed upstream by https://github.com/TeamNewPipe/NewPipe/issues/10930 just needs to be rebased once a release is published

**Comment by heema** [comment]
v0.27.0 has been released

**Comment by javulticat** [comment]
Version `0.27.0-1` of `NewPipe X` (based on upstream's `0.27.0`) will be available soon - just waiting on a graphic designer I'm working with to finish the rebranded `NewPipe X` graphics, as I was planning on releasing the app rebranding at the same time (so that `0.27.0-1` can be made available on F-Droid).

In the interim, I believe this (and several/most? other) issues fixed in upstream's `0.27.0` should be fixed in version `0.26.1-3` (which I had worked on before it became apparent that upstream was going to release `0.27.0`), which is currently available as a debug build [here](https://github.com/NewPipeX/NewPipeX/actions/runs/8823163667/artifacts/1444930222) if anyone is interested in trying it.  I'm hoping to just release `0.27.0-1` instead, but I can release a production build of (pre-rebrand) version `0.26.1-3` to hold us over for a little while if I don't have the necessary graphics to complete the app rebranding in-hand by next week.

Thanks!

**Comment by monstrosities** [comment]
Thanks for this nice project continuation. Any updates on the aforementioned builds or is the debug build the way to go?

**Comment by javulticat** [comment]
Thanks all for your interest and patience; [`v0.27.0-1` of NewPipe X is now available!](https://github.com/NewPipeX/NewPipeX/releases/tag/v0.27.0-1)
